blank_issues_enabled: true
contact_links:
  - name: December Documentation Hub
    url: https://casvt.github.io/December/
    about: You can find the documentation for December here.
  - name: Discord Server
    url: https://discord.gg/kWvhzNwKRV
    about: Get in contact on the discord server.
