name: Contribute Request
description: Announce that you want to contribute to the project
labels: contributing
body:
  - type: textarea
    attributes:
      label: What do you want to contribute?
      description: E.g. add a feature, fix a bug, improve documentation, etc.
    validations:
      required: true

  - type: input
    attributes:
      label: How long do you think it will take to finish it?
      placeholder: E.g. one week, one month, three months, etc.
    validations:
      required: true
