# Site Details
site_name: December Docs
site_description: The official guide for December 
site_author: Casvt
repo_url: https://github.com/Casvt/December
edit_uri: blob/development/docs/
repo_name: Casvt/December
docs_dir: ./pages

# Site appearance (logos, colours, icons)
theme:
  name: material
  language: en
  code_wrap: true
  features:
    - content.tabs.link
    - content.code.copy
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      guess_lang: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3
  - tables

# mkdocs function extensions
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: false

# Navigation Layout
nav:
  - Home: index.md
  - Installation: installation.md
  - Config: config.md
  - Actions: actions.md
